apiVersion: v1
kind: Service
metadata:
  name: k8s-java
  labels:
    app: k8s-java
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 48888

  selector:
    app: k8s-java