apiVersion: extensions/v1beta1
kind: ingress
metadata:
  name: simple-fanout-example
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: test.scajy.cn
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 80