apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment
  labels:
    app: nginx-deployment
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 48889
  selector:
    app: nginx-deployment 